import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";

const INDEX_PATH = path.join(process.cwd(), "apps", "web", "public", "index.html");
const APP_JS_PATH = path.join(process.cwd(), "apps", "web", "public", "app.js");

test("web shell keeps demo-guided control room pages", async () => {
  const html = await readFile(INDEX_PATH, "utf8");

  assert.ok(html.includes('id="projects"'));
  assert.ok(html.includes('id="metricProjectsTotal"'));
  assert.ok(html.includes('id="projectConfigPath"'));
  assert.ok(html.includes('id="runs"'));
  assert.ok(html.includes('id="stage-plans"'));
  assert.ok(html.includes('id="run-detail"'));
  assert.ok(html.includes('id="results"'));
  assert.ok(html.includes('id="review"'));
  assert.ok(html.includes('id="compare"'));
  assert.ok(html.includes('id="commands"'));
  assert.ok(html.includes('id="team"'));
  assert.ok(html.includes('id="settings"'));
  assert.ok(html.includes('id="apiHealthStatus"'));
  assert.ok(html.includes('id="runArtifactsBody"'));
  assert.ok(html.includes('id="runArtifactScope"'));
  assert.ok(html.includes('id="clearPhaseFilterButton"'));
  assert.ok(html.includes('id="artifactPreviewOutput"'));
  assert.ok(html.includes('id="stagePlansTableBody"'));
  assert.ok(html.includes('id="selectedStagePlanStages"'));
  assert.ok(html.includes('id="cliSummaryOutput"'));
  assert.ok(html.includes('id="commandExecutionMode"'));
  assert.ok(html.includes('id="commandConfirmWrites"'));
  assert.ok(html.includes('id="commandStageIdInput"'));
  assert.ok(html.includes('id="commandStagePlanInput"'));
  assert.ok(html.includes('id="commandStopAfterEachStage"'));
  assert.ok(html.includes('id="commandAutoCommit"'));
  assert.ok(html.includes('id="commandCommitMessageInput"'));
  assert.ok(html.includes('id="commandReassessDownstream"'));
  assert.ok(html.includes('id="approvalQueueList"'));
  assert.ok(html.includes('id="selectedReviewSelect"'));
  assert.ok(html.includes('id="reviewCommentsList"'));
  assert.ok(html.includes('id="reviewCommentInput"'));
  assert.ok(html.includes('id="addReviewCommentButton"'));
  assert.ok(html.includes('id="approveReviewButton"'));
  assert.ok(html.includes('id="requestChangesButton"'));
  assert.ok(html.includes('id="reviewPrSummaryOutput"'));
  assert.ok(html.includes('id="reviewAuditOutput"'));
  assert.ok(html.includes('id="settingsConfigPath"'));
  assert.ok(html.includes('id="settingsRunsRoot"'));
  assert.ok(html.includes('id="settingsDefaultModel"'));
  assert.ok(html.includes('id="settingsDefaultMode"'));
  assert.ok(html.includes('id="settingsEvidenceRetention"'));
  assert.ok(html.includes('id="settingsArtifactRetention"'));
  assert.ok(html.includes('id="settingsTheme"'));
  assert.ok(html.includes('id="settingsKeyboardShortcuts"'));
  assert.ok(html.includes('id="saveSettingsButton"'));
  assert.ok(html.includes('id="settingsWriteSafetyPill"'));
  assert.ok(html.includes('id="settingsProvidersBody"'));
  assert.ok(html.includes('id="compareRunAInput"'));
  assert.ok(html.includes('id="compareRunBInput"'));
  assert.ok(html.includes('id="compareRunsButton"'));
  assert.ok(html.includes('id="compareSummaryOutput"'));
  assert.ok(html.includes("docs/ux/web-app-demo.html"));
});

test("web shell is wired to API run data and CLI gateway", async () => {
  const source = await readFile(APP_JS_PATH, "utf8");

  assert.ok(source.includes('fetchJson("/api/health")'));
  assert.ok(source.includes('fetchJson("/api/projects")'));
  assert.ok(source.includes('fetchJson("/api/providers")'));
  assert.ok(source.includes('fetchJson("/api/policy")'));
  assert.ok(source.includes('fetchJson("/api/safety/write-status")'));
  assert.ok(source.includes('fetchJson("/api/settings")'));
  assert.ok(source.includes('fetchJson("/api/settings", {'));
  assert.ok(source.includes('fetchJson("/api/reviews")'));
  assert.ok(source.includes("fetchJson(`/api/projects/${encodeURIComponent(state.selectedProjectId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/projects/${encodeURIComponent(state.selectedProjectId)}/health`)"));
  assert.ok(source.includes('fetchJson("/api/runs")'));
  assert.ok(source.includes('fetchJson("/api/stage-plans")'));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/readiness`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/review`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/evidence`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/phase-artifacts`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/compare?runA=${encodeURIComponent(runA)}&runB=${encodeURIComponent(runB)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/events?limit=80`)"));
  assert.ok(source.includes("fetchJson(`/api/stage-plans/${encodeURIComponent(stagePlanId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/artifacts`)"));
  assert.ok(source.includes('/artifacts/${encodeURIComponent(artifactId)}/content?maxBytes=256000'));
  assert.ok(source.includes('fetchJson("/api/cli/events/recent?limit=80")'));
  assert.ok(source.includes('fetch("/api/cli/commands"'));
  assert.ok(source.includes('fetch("/api/cli/commands/preview"'));
  assert.ok(source.includes("fetchJson(`/api/reviews/${encodeURIComponent(review.id)}/comments`"));
  assert.ok(source.includes("fetchJson(`/api/reviews/${encodeURIComponent(review.id)}/approval`"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(review.runId)}/artifacts`)"));
  assert.ok(source.includes("/artifacts/${encodeURIComponent(prSummaryArtifact.id)}/content?maxBytes=64000"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(review.runId)}/events?limit=40`)"));
  assert.ok(source.includes('new EventSource("/api/cli/events")'));
  assert.ok(source.includes("buildGatewayPayload"));
  assert.ok(source.includes('"fix-stage"'));
  assert.ok(source.includes('"check-write-safety"'));
  assert.ok(source.includes('"probe-opencode"'));
  assert.ok(source.includes('"run-stage"'));
  assert.ok(source.includes('"run-stages"'));
  assert.ok(source.includes('"continue-stages"'));
  assert.ok(source.includes('"accept-stage"'));
  assert.ok(source.includes('"reassess-stage-plan"'));
  assert.ok(source.includes("stagePlanArg"));
  assert.ok(source.includes("reassessDownstream"));
  assert.ok(source.includes("CONFIRMATION_REQUIRED"));
  assert.ok(source.includes("WRITE_MODE_REQUIRED"));
  assert.ok(source.includes("appendCommandEvent"));
  assert.ok(source.includes("appendLifecycleEvent"));
  assert.ok(source.includes("renderApprovalQueue"));
});
