import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";

const ROOT_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "page.tsx");
const CONTROL_ROOM_SHELL_PATH = path.join(process.cwd(), "apps", "web", "app", "_components", "control-room-shell.tsx");
const SIDEBAR_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sidebar.html");
const TOPBAR_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "topbar.html");
const PROJECTS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "projects.html");
const RUNS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "runs.html");
const STAGE_PLANS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "stage-plans.html");
const RUN_DETAIL_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "run-detail.html");
const RESULTS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "results.html");
const REVIEW_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "review.html");
const COMPARE_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "compare.html");
const COMMANDS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "commands.html");
const TEAM_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "team.html");
const SETTINGS_FRAGMENT_PATH = path.join(process.cwd(), "apps", "web", "app", "_fragments", "sections", "settings.html");
const PROJECTS_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "projects", "page.tsx");
const RUNS_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "runs", "page.tsx");
const RUN_DETAIL_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "runs", "[id]", "page.tsx");
const RESULTS_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "results", "[id]", "page.tsx");
const REVIEW_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "review", "[id]", "page.tsx");
const COMMANDS_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "commands", "page.tsx");
const SETTINGS_PAGE_PATH = path.join(process.cwd(), "apps", "web", "app", "settings", "page.tsx");
const GLOBALS_CSS_PATH = path.join(process.cwd(), "apps", "web", "app", "globals.css");
const APP_JS_PATH = path.join(process.cwd(), "apps", "web", "public", "app.js");

test("web shell keeps demo-guided control room pages", async () => {
  const rootPage = await readFile(ROOT_PAGE_PATH, "utf8");
  const shellComponent = await readFile(CONTROL_ROOM_SHELL_PATH, "utf8");
  const projectsPage = await readFile(PROJECTS_PAGE_PATH, "utf8");
  const runsPage = await readFile(RUNS_PAGE_PATH, "utf8");
  const runDetailPage = await readFile(RUN_DETAIL_PAGE_PATH, "utf8");
  const resultsPage = await readFile(RESULTS_PAGE_PATH, "utf8");
  const reviewPage = await readFile(REVIEW_PAGE_PATH, "utf8");
  const commandsPage = await readFile(COMMANDS_PAGE_PATH, "utf8");
  const settingsPage = await readFile(SETTINGS_PAGE_PATH, "utf8");
  const sidebar = await readFile(SIDEBAR_FRAGMENT_PATH, "utf8");
  const topbar = await readFile(TOPBAR_FRAGMENT_PATH, "utf8");
  const projects = await readFile(PROJECTS_FRAGMENT_PATH, "utf8");
  const runs = await readFile(RUNS_FRAGMENT_PATH, "utf8");
  const stagePlans = await readFile(STAGE_PLANS_FRAGMENT_PATH, "utf8");
  const runDetail = await readFile(RUN_DETAIL_FRAGMENT_PATH, "utf8");
  const results = await readFile(RESULTS_FRAGMENT_PATH, "utf8");
  const review = await readFile(REVIEW_FRAGMENT_PATH, "utf8");
  const compare = await readFile(COMPARE_FRAGMENT_PATH, "utf8");
  const commands = await readFile(COMMANDS_FRAGMENT_PATH, "utf8");
  const team = await readFile(TEAM_FRAGMENT_PATH, "utf8");
  const settings = await readFile(SETTINGS_FRAGMENT_PATH, "utf8");
  const html = [sidebar, topbar, projects, runs, stagePlans, runDetail, results, review, compare, commands, team, settings].join("\n");
  const css = await readFile(GLOBALS_CSS_PATH, "utf8");

  assert.ok(rootPage.includes('redirect("/projects")'));
  assert.ok(shellComponent.includes("window.__MERGEWRIGHT_API_BASE_URL__"));
  assert.ok(shellComponent.includes("window.__MERGEWRIGHT_WEB_ROUTE__"));
  assert.ok(shellComponent.includes('Script src="/app.js"'));
  assert.ok(shellComponent.includes("sidebar.html"));
  assert.ok(shellComponent.includes("sectionsRoot"));
  assert.ok(shellComponent.includes("projects.html"));
  assert.ok(projectsPage.includes('page: "projects"'));
  assert.ok(runsPage.includes('page: "runs"'));
  assert.ok(runDetailPage.includes('page: "run-detail"'));
  assert.ok(resultsPage.includes('page: "results"'));
  assert.ok(reviewPage.includes('page: "review"'));
  assert.ok(commandsPage.includes('page: "commands"'));
  assert.ok(settingsPage.includes('page: "settings"'));
  assert.ok(css.includes(".app { min-height: 100vh;"));

  assert.ok(html.includes('id="projects"'));
  assert.ok(html.includes('id="metricProjectsTotal"'));
  assert.ok(html.includes('id="projectConfigPath"'));
  assert.ok(html.includes('id="runs"'));
  assert.ok(html.includes('id="stage-plans"'));
  assert.ok(html.includes('id="run-detail"'));
  assert.ok(html.includes('id="results"'));
  assert.ok(html.includes('id="review"'));
  assert.ok(html.includes('id="compare"'));
  assert.ok(html.includes('id="commands"'));
  assert.ok(html.includes('id="team"'));
  assert.ok(html.includes('id="settings"'));
  assert.ok(html.includes('id="apiHealthStatus"'));
  assert.ok(html.includes('id="runArtifactsBody"'));
  assert.ok(html.includes('id="runArtifactScope"'));
  assert.ok(html.includes('id="clearPhaseFilterButton"'));
  assert.ok(html.includes('id="artifactPreviewOutput"'));
  assert.ok(html.includes('id="stagePlansTableBody"'));
  assert.ok(html.includes('id="selectedStagePlanStages"'));
  assert.ok(html.includes('id="cliSummaryOutput"'));
  assert.ok(html.includes('id="commandExecutionMode"'));
  assert.ok(html.includes('id="commandConfirmWrites"'));
  assert.ok(html.includes('id="commandStageIdInput"'));
  assert.ok(html.includes('id="commandStagePlanInput"'));
  assert.ok(html.includes('id="commandStopAfterEachStage"'));
  assert.ok(html.includes('id="commandAutoCommit"'));
  assert.ok(html.includes('id="commandCommitMessageInput"'));
  assert.ok(html.includes('id="commandReassessDownstream"'));
  assert.ok(html.includes('id="approvalQueueList"'));
  assert.ok(html.includes('id="selectedReviewSelect"'));
  assert.ok(html.includes('id="reviewCommentsList"'));
  assert.ok(html.includes('id="reviewCommentInput"'));
  assert.ok(html.includes('id="addReviewCommentButton"'));
  assert.ok(html.includes('id="approveReviewButton"'));
  assert.ok(html.includes('id="requestChangesButton"'));
  assert.ok(html.includes('id="reviewPrSummaryOutput"'));
  assert.ok(html.includes('id="reviewAuditOutput"'));
  assert.ok(html.includes('id="settingsConfigPath"'));
  assert.ok(html.includes('id="settingsRunsRoot"'));
  assert.ok(html.includes('id="settingsDefaultModel"'));
  assert.ok(html.includes('id="settingsDefaultMode"'));
  assert.ok(html.includes('id="settingsEvidenceRetention"'));
  assert.ok(html.includes('id="settingsArtifactRetention"'));
  assert.ok(html.includes('id="settingsTheme"'));
  assert.ok(html.includes('id="settingsKeyboardShortcuts"'));
  assert.ok(html.includes('id="saveSettingsButton"'));
  assert.ok(html.includes('id="settingsWriteSafetyPill"'));
  assert.ok(html.includes('id="settingsProvidersBody"'));
  assert.ok(html.includes('id="compareRunAInput"'));
  assert.ok(html.includes('id="compareRunBInput"'));
  assert.ok(html.includes('id="compareRunsButton"'));
  assert.ok(html.includes('id="compareSummaryOutput"'));
  assert.ok(html.includes("docs/ux/web-app-demo.html"));
});

test("web shell is wired to API run data and CLI gateway", async () => {
  const source = await readFile(APP_JS_PATH, "utf8");

  assert.ok(source.includes('const API_BASE_URL = (window.__MERGEWRIGHT_API_BASE_URL__ ?? "http://127.0.0.1:3040")'));
  assert.ok(source.includes("const routeContext = window.__MERGEWRIGHT_WEB_ROUTE__"));
  assert.ok(source.includes("function toApiUrl(url)"));
  assert.ok(source.includes("function navigateToPage(id)"));
  assert.ok(source.includes("window.location.assign(route)"));
  assert.ok(source.includes('fetchJson("/api/health")'));
  assert.ok(source.includes('fetchJson("/api/projects")'));
  assert.ok(source.includes('fetchJson("/api/providers")'));
  assert.ok(source.includes('fetchJson("/api/policy")'));
  assert.ok(source.includes('fetchJson("/api/safety/write-status")'));
  assert.ok(source.includes('fetchJson("/api/settings")'));
  assert.ok(source.includes('fetchJson("/api/settings", {'));
  assert.ok(source.includes('fetchJson("/api/reviews")'));
  assert.ok(source.includes("fetchJson(`/api/projects/${encodeURIComponent(state.selectedProjectId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/projects/${encodeURIComponent(state.selectedProjectId)}/health`)"));
  assert.ok(source.includes('fetchJson("/api/runs")'));
  assert.ok(source.includes('fetchJson("/api/stage-plans")'));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/readiness`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/review`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/evidence`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/phase-artifacts`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/compare?runA=${encodeURIComponent(runA)}&runB=${encodeURIComponent(runB)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/events?limit=80`)"));
  assert.ok(source.includes("fetchJson(`/api/stage-plans/${encodeURIComponent(stagePlanId)}`)"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(runId)}/artifacts`)"));
  assert.ok(source.includes('/artifacts/${encodeURIComponent(artifactId)}/content?maxBytes=256000'));
  assert.ok(source.includes('fetchJson("/api/cli/events/recent?limit=80")'));
  assert.ok(source.includes('fetch(toApiUrl("/api/cli/commands"'));
  assert.ok(source.includes('fetch(toApiUrl("/api/cli/commands/preview"'));
  assert.ok(source.includes("fetchJson(`/api/reviews/${encodeURIComponent(review.id)}/comments`"));
  assert.ok(source.includes("fetchJson(`/api/reviews/${encodeURIComponent(review.id)}/approval`"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(review.runId)}/artifacts`)"));
  assert.ok(source.includes("/artifacts/${encodeURIComponent(prSummaryArtifact.id)}/content?maxBytes=64000"));
  assert.ok(source.includes("fetchJson(`/api/runs/${encodeURIComponent(review.runId)}/events?limit=40`)"));
  assert.ok(source.includes('new EventSource(toApiUrl("/api/cli/events"))'));
  assert.ok(source.includes("buildGatewayPayload"));
  assert.ok(source.includes('"fix-stage"'));
  assert.ok(source.includes('"check-write-safety"'));
  assert.ok(source.includes('"probe-opencode"'));
  assert.ok(source.includes('"run-stage"'));
  assert.ok(source.includes('"run-stages"'));
  assert.ok(source.includes('"continue-stages"'));
  assert.ok(source.includes('"accept-stage"'));
  assert.ok(source.includes('"reassess-stage-plan"'));
  assert.ok(source.includes("stagePlanArg"));
  assert.ok(source.includes("reassessDownstream"));
  assert.ok(source.includes("CONFIRMATION_REQUIRED"));
  assert.ok(source.includes("WRITE_MODE_REQUIRED"));
  assert.ok(source.includes("appendCommandEvent"));
  assert.ok(source.includes("appendLifecycleEvent"));
  assert.ok(source.includes("renderApprovalQueue"));
});
